### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by rehmatworks** [facundoolano/google-play-api#12]
API server was working just fine but it stopped working recently. Here is the debug log when executing `npm start` command. Please have a look at this issue:

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle google-play-api@1.0.0~prestart: google-play-api@1.0.0
6 info lifecycle google-play-api@1.0.0~start: google-play-api@1.0.0
7 verbose lifecycle google-play-api@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle google-play-api@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/users/serverpilot/google-play-scrapper/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle google-play-api@1.0.0~start: CWD: /srv/users/serverpilot/google-play-scrapper
10 silly lifecycle google-play-api@1.0.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle google-play-api@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle google-play-api@1.0.0~start: Failed to exec start script
13 verbose stack Error: google-play-api@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid google-play-api@1.0.0
15 verbose cwd /srv/users/serverpilot/google-play-scrapper
16 verbose Linux 4.9.68-x86_64-linode89
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error google-play-api@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the google-play-api@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rehmatworks** [comment]
My bad, the port was already in use. Sorry for this.
